# Generated by Django 5.2.9 on 2025-12-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_description_project_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='dashboard_url',
            field=models.CharField(blank=True, help_text='내부 대시보드 경로 (/dashboard/ 등)', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub 저장소 URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
